version: '3.1'
services:
  web:
    container_name: ${WEB_HOST}
    image: ${WEB_IMAGE_NAME}:${WEB_IMAGE_TAG}
    depends_on:
      - db
    ports:
      - "${WEB_PORT}:8069"
    volumes:
      - ./odoo_web:/var/lib/odoo/
      - ./odoo_conf:/etc/odoo
      - ./addons:/mnt/extra-addons
      - ./addons-customize:/mnt/extra-addons-customize
    entrypoint: "/usr/bin/odoo -c /etc/odoo/odoo.conf"
  db:
    container_name: ${DB_HOST}
    image: ${DB_IMAGE}:${DB_TAG}
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_PASSWORD=${DB_PASSWD}
      - POSTGRES_USER=${DB_USER}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - ./odoo_postgresdata:/var/lib/postgresql/data/pgdata
