name: Deploy to VPS

on:
  push:
    branches:
      - main  # Cambia a la rama que usas para despliegue

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
        name: id_rsa
        if_key_exists: fail

    - name: Deploy to VPS
      run: |
        ssh -o StrictHostKeyChecking=no root@92.118.56.248 << EOF
          cd /home/administrator/proticket
          git pull origin main
          docker-compose up -d
        EOF
