name: Deploy to VPS

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Copy files to VPS
        run: |
          scp -r . ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }}:/home/administrator/proticket  # Cambia la ruta según tu proyecto

      - name: Deploy with Docker Compose
        run: |
          ssh ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} "cd /home/administrator/proticket && docker-compose down && docker-compose up -d --build"
