name: Deploy

on:
  push:
    branches:
      - main  # O la rama que utilices para desplegar

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          ssh-passphrase: ${{ secrets.SSH_PASSPHRASE }}

      - name: Deploy to server
        run: |
          ssh root@92.118.56.248 'cd /home/administrator/proticket && docker-compose up -d'
