jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        if [ -z "$SSH_HOST" ]; then
          echo "Error: SSH_HOST is not set"
          exit 1
        fi
        ssh-keyscan -H $SSH_HOST >> ~/.ssh/known_hosts
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        SSH_HOST: ${{ secrets.SSH_HOST }}  # Definido desde los secretos

    - name: Deploy code via SSH
      run: |
        ssh -i ~/.ssh/id_rsa root@$SSH_HOST "cd /home/administrator/proticket && git checkout main && git pull && exit"
      env:
        SSH_HOST: ${{ secrets.SSH_HOST }}
